name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - name: Install build dependencies
        run: apt-get update && apt-get install -y \
          gcc \
          libjpeg-dev

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --all-extras

      - name: Build wheel
        run: uv build

      - name: Publish package
        run: uv publish